export const themes = {
  verde: {
    name: "verde",
    colors: {
      primary: "#2563eb",
      secondary: "#1e40af",
      backgroundColorA: "#dddddd",
      backgroundColorB: "#ffffff",
      accent: "#ff0000",
      text: "#1f2937",
      textMenubar: "#444444",
      textMenubarButton: "#dddddd",
      logoLinkColor: "#191919",
      shadowColor: "#818181",
      bgMenubar: "#dddddd",
      bgMenubarButton: "#969696",
      bgMenucontainerColorA: "#818181",
      bgMenucontainerColorB: "#000000",
      fadedCircleBg: "#818181",
      gradientCircleBg: "#818181",
      homeCardTitleFontColor: "#818181",
      homeCardFontColor: "#818181",
      homeCardBgColor: "#dddddd",
      homeCardBordersColor: "#ff0000",
      homeCardIconBgColor: "#818181",
      homeCardIconColor: "#dddddd",
    },
  },
  azul: {
    name: "azul",
    colors: {
      primary: "#3b82f6",
      secondary: "#1e40af",
      backgroundColorA: "#1f2937",
      backgroundColorB: "#1a62c0",
      accent: "#f59e0b",
      text: "#f9fafb",
      textMenubar: "#dddddd",
      textMenubarButton: "#3f3f3f",
      logoLinkColor: "#f9fafb",
      shadowColor: "#cccccc",
      bgMenubar: "#222222",
      bgMenubarButton: "#dddddd",
      bgMenucontainerColorA: "#4d4d4d",
      bgMenucontainerColorB: "#0d0d33",
      fadedCircleBg: "#cfe5ff",
      gradientCircleBg: "#cfe5ff",
      homeCardTitleFontColor: "#818181",
      homeCardFontColor: "#818181",
      homeCardBgColor: "#dddddd",
      homeCardBordersColor: "#f59e0b",
      homeCardIconBgColor: "#818181",
      homeCardIconColor: "#dddddd",
    },
  },
};